version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    depends_on:
      - book-service
      - category-service
      - user-service
    ports:
      - "8000:8000"
    environment:
      - BOOK_SERVICE_HOST=book-service
      - BOOK_SERVICE_PORT=50051
      - CATEGORY_SERVICE_HOST=category-service
      - CATEGORY_SERVICE_PORT=50052
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=50053
      - SERVER_PORT=8000
    networks:
      - library-network
    restart: on-failure

  book-service:
    build:
      context: ./book-service
    depends_on:
      - book-db
      - category-service
      - redis
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - DB_HOST=book-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=book_service
      - DB_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CATEGORY_SERVICE_HOST=category-service
      - CATEGORY_SERVICE_PORT=50052
      - SERVER_PORT=8080
      - GRPC_PORT=50051
    networks:
      - library-network
    restart: on-failure

  category-service:
    build:
      context: ./category-service
    depends_on:
      - category-db
    ports:
      - "8081:8081"
      - "50052:50052"
    environment:
      - DB_HOST=category-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=category_service
      - DB_SSLMODE=disable
      - SERVER_PORT=8081
      - GRPC_PORT=50052
    networks:
      - library-network
    restart: on-failure

  user-service:
    build:
      context: ./user-service
    depends_on:
      - user-db
      - redis
    ports:
      - "8082:8082"
      - "50053:50053"
    environment:
      - DB_HOST=user-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=user_service
      - DB_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=8082
      - GRPC_PORT=50053
      - JWT_SECRET=your-secure-jwt-secret-key-change-in-production
      - JWT_EXPIRY=3600
      - REFRESH_TOKEN=86400
    networks:
      - library-network
    restart: on-failure

  book-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=book_service
    volumes:
      - book-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - library-network
    restart: on-failure

  category-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=category_service
    volumes:
      - category-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - library-network
    restart: on-failure

  user-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_service
    volumes:
      - user-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - library-network
    restart: on-failure

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - library-network
    restart: on-failure

networks:
  library-network:
    driver: bridge

volumes:
  book-data:
  category-data:
  user-data:
  redis-data: